version: "3"
services:
    app:
        build: .
        links:
            - postgres
            - redis
        ports:
            - 8000:8000
        volumes:
            - .:/application
            - ~/.ssh:/root/.ssh
            - server-logs:/application/logs
            - server-site-packages:/usr/local/lib/python3.8/site-packages
            - server-usr-local-bin:/usr/local/bin
        command: python server/manage.py runserver 0:8000
        working_dir: /application
        env_file:
            - ./server/config/.env
        entrypoint: /application/script/entrypoint.sh

    postgres:
        image: postgres:12
        env_file:
            - ./server/config/.env
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
            - 5432:5432
        volumes:
            - .:/shared
            - postgres-data:/var/lib/postgresql/data
            - ./db_scripts:/docker-entrypoint-initdb.d/

    redis:
        image: "redis:latest"

volumes:
    server-site-packages:
        driver: local
    postgres-data:
        driver: local
    server-logs:
        driver: local
    server-usr-local-bin:
        driver: local
